title: Misuse Co
author: Paul Theriault
email: paul@misuse.co
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Paul Theriault.
theme: minima

# social links
twitter_username: creativemisuse # DO NOT include the @ character, or else the build will fail!
github_username:  pauljt # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
